services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    container_name: db_avito_test_task
    expose:
      - 5432
    ports:
      - '5433:5432'

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'make start'
    env_file:
      - .env
    container_name: avito_test_task
    environment:
      POSTGRES_HOST: db
    volumes:
      - .:/usr/local/src/avito_test_task
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  postgres_volume: