"""empty message

Revision ID: cdab4cec1258
Revises: 6490c4bdc62e
Create Date: 2024-06-06 17:34:20.919872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdab4cec1258'
down_revision: Union[str, None] = '6490c4bdc62e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistic', sa.Column('cpc', sa.Numeric(precision=15, scale=3), sa.Computed('cost / NULLIF(clicks, 0)', ), nullable=True))
    op.add_column('statistic', sa.Column('cpm', sa.Numeric(precision=15, scale=3), sa.Computed('cost / NULLIF(views, 0) * 1000', ), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistic', 'cpm')
    op.drop_column('statistic', 'cpc')
    # ### end Alembic commands ###
